//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace complejos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancha
    {
        public cancha()
        {
            this.reserva = new HashSet<reserva>();
        }
    
        public int id_cancha { get; set; }
        public Nullable<int> id_complejo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public Nullable<int> horarios { get; set; }
        public Nullable<bool> disponible { get; set; }
        public Nullable<int> horas { get; set; }
    
        public virtual horas horas1 { get; set; }
        public virtual complejo complejo { get; set; }
        public virtual tipo_cancha tipo_cancha { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
