//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace complejos2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Complejos2Entities : DbContext
    {
        public Complejos2Entities()
            : base("name=Complejos2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cancha> cancha { get; set; }
        public DbSet<complejo> complejo { get; set; }
        public DbSet<horas> horas { get; set; }
        public DbSet<reserva> reserva { get; set; }
        public DbSet<tipo_cancha> tipo_cancha { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
