//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace complejos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complejo
    {
        public complejo()
        {
            this.cancha = new HashSet<cancha>();
        }
    
        public Nullable<int> dueño { get; set; }
        public int id_complejo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int numero_de_canchas { get; set; }
        public string telefono_complejo { get; set; }
        public string mail { get; set; }
        public string facebook { get; set; }
    
        public virtual ICollection<cancha> cancha { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
