//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace complejos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id_reserva { get; set; }
        public Nullable<int> usuario_que_alquila { get; set; }
        public Nullable<int> cancha_alquilada { get; set; }
        public Nullable<System.DateTime> fecha_efectuado_alquiler { get; set; }
        public Nullable<System.TimeSpan> hora_ectuado_alquiler { get; set; }
        public Nullable<int> hora_a_jugar { get; set; }
    
        public virtual cancha cancha { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
