//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace complejos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.complejo = new HashSet<complejo>();
            this.reserva = new HashSet<reserva>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string apellido_usuario { get; set; }
        public string email_usuario { get; set; }
        public string telefono_usuario { get; set; }
        public Nullable<int> rol { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> canchas_alquiladas { get; set; }
        public Nullable<int> reputacion { get; set; }
    
        public virtual ICollection<complejo> complejo { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
